---
title: 'Decisiones públicas del Estado Peruano frente al COVID-19'
output: html_document
---

<p>
<div style="text-align:justify"> Este portal es un esfuerzo conjunto para realizar un monitoreo de las decisiones políticas adoptadas por el gobierno peruano en respuesta a la pandemia del nuevo coronavirus (SARS-CoV-2). El objetivo principal es la aplicación de una serie de conceptos para el estudio de políticas públicas como instrumentos de políticas, conflictividad social, redes de coordinación, agenda de problemas públicos, entre otros. Parte de la idea de construir un repositorio de las medidas adoptadas durante la emergencia sanitaria para la reflexión sobre la respuesta del Estado Peruano. </div>
</p>


##### ¿Qué encontrarás en este portal?

1. [Evolución del COVID-19 en el Perú](https://covid-19-proyectoperu.github.io/casos.html)

2. [Seguimiento nacional](https://covid-19-proyectoperu.github.io/nacional.html)

3. [Seguimiento sub-nacional](https://covid-19-proyectoperu.github.io/subnacional.html)


##### Responsables del portal

* Seguimiento nacional:
  
  Alonso Tovar Rojas  
  Carol Pflücker Romero  
  Luisa Carranza Avalos  
  Carlos Andres Guevara

* Seguimiento subnacional:

  Maira Chagua Taype  
  Berenisse Rivera Alarcón  
  Elizabeth Trujillo  
  Joshua Gamero  
  
* Editores del portal:  

  Alonso Tovar Rojas  
  Manuel Ponte Torrel  


 
### Para sumarse al equipo

<p>
<div style="text-align:justify"> Este portal esta abierto a toda colaboración, aquellos que tengan interes en apoyar en el seguimiento de los datos de alguna sección (datos, nacional, sub-nacional) y/o proponer agregar apartados en las secciones. Para sumarse en el proyecto pueden escribir a [Alonso Tovar](mailto:a.tovar1498@gmail.com). Los colaboradores deben estar disponibles para una constante actualizacion de la información del portal.</div>
</p>


<p>
<div style="text-align:justify"> Para solicitar información, reportar fallas y/o contribuir con comentarios de mejora, comunicarse al correo electrónico: [**covid19.proyectoperu@gmail.com**](mailto:covid19.proyectoperu@gmail.com) </div>
</p>


