---
title: "Casos positivos a nivel distrital"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(gifski)
library(gganimate)
library(plotly)
library(dplyr)
library(ggiraph)
library(rio)
library(sp)
library(geojsonio)
library(rgdal)
library(spdep)
library(pgirmess)
library(gstat)
library(maps)
library(rgeos) 
library(gtable)
library(scales)
library(ggplot2)
library(rgdal)
library(maptools)
library(Matrix)
library(LearnBayes)
library(spatstat)
library(googleVis)
library(plyr)
library(maptools)
library(leaflet)
library(htmlwidgets)
library(devtools)
```


### Región: Amazonas

```{r Amazonas Data, include=FALSE}
distrito <- readOGR(dsn="/cloud/project/subnacional_files",layer="DISTRITOS")
datos_distrito=import("/cloud/project/subnacional_files/Seguimiento_Sub_nacional.xlsx", sheet="DatosDistrital_Mapa")
amazonas <- distrito[distrito$DEPARTAMEN == "AMAZONAS",]

amazonascondata=merge(amazonas,datos_distrito,by.x="IDDIST",by.y="IDDIST")
```


```{r amazonas Codigo, include=FALSE}
popup_amazonas <- paste0("<b>", "Departamento: ", "</b>", as.character(amazonascondata$DEPARTAMENTO), "<br>",
                "<b>", "Provincia: ", "</b>", as.character(amazonascondata$PROVINCIA.y), "<br>",
                "<b>", "Distrito: ", "</b>", as.character(amazonascondata$DISTRITO.y), "<br>",
                "<b>", "Casos Positivos: ", "</b>", as.character(amazonascondata$Casos_Positivos), "<br>")

palfac_amazonas <- colorFactor(palette=c("#ffffcc","#a1dab4","#41b6c4","#800000","#636363"), domain = amazonascondata$Categoria)

amazonas_mapa <- leaflet(amazonascondata) %>% addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5, opacity = 1,
              fillOpacity = 0.5, fillColor = ~palfac_amazonas(amazonascondata$Categoria), group = "Belleza",
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE), 
              label = ~amazonascondata$DISTRITO.y, labelOptions = labelOptions(direction = "auto"), popup = popup_amazonas) %>%
  addLegend(position = "topright", pal = palfac_amazonas, values = ~amazonascondata$Categoria,
            title = "% de casos positivos por región")
```


```{r amazonas Mapa, eval=TRUE, echo=FALSE, fig.width=3.5, fig.align='center',message=FALSE,warning=FALSE}
amazonas_mapa
```





### Región: Madre de Dios

```{r Madre de Dios Data, include=FALSE}
distrito <- readOGR(dsn="/cloud/project/subnacional_files",layer="DISTRITOS")
datos_distrito=import("/cloud/project/subnacional_files/Seguimiento_Sub_nacional.xlsx", sheet="DatosDistrital_Mapa")
madrededios <- distrito[distrito$DEPARTAMEN == "MADRE DE DIOS",]

madrededioscondata=merge(madrededios,datos_distrito,by.x="IDDIST",by.y="IDDIST")
```



```{r Madre de Dios Codigo, include=FALSE}
popup_madrededios <- paste0("<b>", "Departamento: ", "</b>", as.character(madrededioscondata$DEPARTAMENTO), "<br>",
                "<b>", "Provincia: ", "</b>", as.character(madrededioscondata$PROVINCIA.y), "<br>",
                "<b>", "Distrito: ", "</b>", as.character(madrededioscondata$DISTRITO.y), "<br>",
                "<b>", "Casos Positivos: ", "</b>", as.character(madrededioscondata$Casos_Positivos), "<br>")

palfac_madrededios <- colorFactor(palette=c("#ffffcc","#a1dab4","#800000","#636363"), domain = madrededioscondata$Categoria)

madrededios_mapa <- leaflet(madrededioscondata) %>% addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5, opacity = 1,
              fillOpacity = 0.5, fillColor = ~palfac_madrededios(madrededioscondata$Categoria), group = "Belleza",
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE), 
              label = ~madrededioscondata$DISTRITO.y, labelOptions = labelOptions(direction = "auto"), popup = popup_madrededios) %>%
  addLegend(position = "topright", pal = palfac_madrededios, values = ~madrededioscondata$Categoria,
            title = "% de casos positivos en la región")
```


```{r Madre de Dios Mapa, eval=TRUE, echo=FALSE, fig.width=3.5, fig.align='center', message=FALSE,warning=FALSE}
madrededios_mapa
```

### Región: San Martin

```{r San Martin Data, include=FALSE}
distrito <- readOGR(dsn="/cloud/project/subnacional_files",layer="DISTRITOS")
datos_distrito=import("/cloud/project/subnacional_files/Seguimiento_Sub_nacional.xlsx", sheet="DatosDistrital_Mapa")
sanmartin <- distrito[distrito$DEPARTAMEN == "SAN MARTIN",]

sanmartincondata=merge(sanmartin,datos_distrito,by.x="IDDIST",by.y="IDDIST")
```


```{r San Martin Codigo, include=FALSE}
popup_sanmartin <- paste0("<b>", "Departamento: ", "</b>", as.character(sanmartincondata$DEPARTAMENTO), "<br>",
                "<b>", "Provincia: ", "</b>", as.character(sanmartincondata$PROVINCIA.y), "<br>",
                "<b>", "Distrito: ", "</b>", as.character(sanmartincondata$DISTRITO.y), "<br>",
                "<b>", "Casos Positivos: ", "</b>", as.character(sanmartincondata$Casos_Positivos), "<br>")

palfac_sanmartin <- colorFactor(palette=c("#ffffcc","#a1dab4","#41b6c4","#225ea8","#636363"), domain = sanmartincondata$Categoria)

Sanmartin_mapa <- leaflet(sanmartincondata) %>% addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5, opacity = 1,
              fillOpacity = 0.5, fillColor = ~palfac_sanmartin(sanmartincondata$Categoria), group = "Belleza",
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE), 
              label = ~sanmartincondata$DISTRITO.y, labelOptions = labelOptions(direction = "auto"), popup = popup_sanmartin) %>%
  addLegend(position = "topright", pal = palfac_sanmartin, values = ~sanmartincondata$Categoria,
            title = "% de casos positivos por distrito")
```


```{r San Martin Mapa, eval=TRUE, echo=FALSE, fig.width=3.5, fig.align='center',message=FALSE,warning=FALSE}
Sanmartin_mapa
```

### Región: Tumbes

```{r Tumbes Data, include=FALSE}
distrito <- readOGR(dsn="/cloud/project/subnacional_files",layer="DISTRITOS")
datos_distrito=import("/cloud/project/subnacional_files/Seguimiento_Sub_nacional.xlsx", sheet="DatosDistrital_Mapa")
tumbes <- distrito[distrito$DEPARTAMEN == "TUMBES",]

tumbescondata=merge(tumbes,datos_distrito,by.x="IDDIST",by.y="IDDIST")
```


```{r Tumbes Codigo, include=FALSE}
popup_tumbes <- paste0("<b>", "Departamento: ", "</b>", as.character(tumbescondata$DEPARTAMENTO), "<br>",
                "<b>", "Provincia: ", "</b>", as.character(tumbescondata$PROVINCIA.y), "<br>",
                "<b>", "Distrito: ", "</b>", as.character(tumbescondata$DISTRITO.y), "<br>",
                "<b>", "Casos Positivos: ", "</b>", as.character(tumbescondata$Casos_Positivos), "<br>")

palfac_tumbes <- colorFactor(palette=c("#ffffcc","#a1dab4","#41b6c4","#800000","#636363"), domain = tumbescondata$Categoria)

tumbes_mapa <- leaflet(tumbescondata) %>% addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5, opacity = 1,
              fillOpacity = 0.5, fillColor = ~palfac_tumbes(tumbescondata$Categoria), group = "Belleza",
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE), 
              label = ~tumbescondata$DISTRITO.y, labelOptions = labelOptions(direction = "auto"), popup = popup_tumbes) %>%
  addLegend(position = "topright", pal = palfac_tumbes, values = ~tumbescondata$Categoria,
            title = "% de casos positivos por distrito")
```


```{r Tumbes Mapa, eval=TRUE, echo=FALSE, fig.width=3.5, fig.align='center',message=FALSE,warning=FALSE}
tumbes_mapa
```

### Región: Cajamarca

```{r Cajamarca Data, include=FALSE}
distrito <- readOGR(dsn="/cloud/project/subnacional_files",layer="DISTRITOS")
datos_distrito=import("/cloud/project/subnacional_files/Seguimiento_Sub_nacional.xlsx", sheet="DatosDistrital_Mapa")
cajamarca <- distrito[distrito$DEPARTAMEN == "CAJAMARCA",]

cajamarcacondata=merge(cajamarca,datos_distrito,by.x="IDDIST",by.y="IDDIST")
```


```{r Cajamarca Codigo, include=FALSE}
popup_cajamarca <- paste0("<b>", "Departamento: ", "</b>", as.character(cajamarcacondata$DEPARTAMENTO), "<br>",
                "<b>", "Provincia: ", "</b>", as.character(cajamarcacondata$PROVINCIA.y), "<br>",
                "<b>", "Distrito: ", "</b>", as.character(cajamarcacondata$DISTRITO.y), "<br>",
                "<b>", "Casos Positivos: ", "</b>", as.character(cajamarcacondata$Casos_Positivos), "<br>")

palfac_cajamarca <- colorFactor(palette=c("#ffffcc","#a1dab4","#41b6c4","#800000","#636363"), domain = cajamarcacondata$Categoria)

cajamarca_mapa <- leaflet(cajamarcacondata) %>% addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5, opacity = 1,
              fillOpacity = 0.5, fillColor = ~palfac_cajamarca(cajamarcacondata$Categoria), group = "Belleza",
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE), 
              label = ~cajamarcacondata$DISTRITO.y, labelOptions = labelOptions(direction = "auto"), popup = popup_cajamarca) %>%
  addLegend(position = "topright", pal = palfac_cajamarca, values = ~cajamarcacondata$Categoria,
            title = "% de casos positivos por distrito")
```


```{r Cajamarca Mapa, eval=TRUE, echo=FALSE, fig.width=3.5, fig.align='center',message=FALSE,warning=FALSE}
cajamarca_mapa
```

