---
title: "Seguimiento sub-nacional"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 3.1. Gobiernos regionales

#### 3.1.1. Datos sobre casos y muestras realizadas

```{r, echo=FALSE,eval=TRUE,warning=FALSE,message=FALSE,error=FALSE}
### cargar datos

regioneslink="https://docs.google.com/spreadsheets/d/e/2PACX-1vQkc4tZ-ZXIUtZ6CZPEarncXxE3lFMD8Tp4MahTcc-hMw2XdAbn5nSPLFwvM-6YoAv3l05t9ggK0bv-/pub?gid=1102095429&single=true&output=csv"

regiones=as.data.frame(read.csv(regioneslink))


### contruir tabla
#install.packages("dplyr")
library(dplyr)
regiones%>%
  dplyr::select("Región"="region","Muestras realizadas"="muestras_regionales", "Positivos"="casos_positivos", "Muestras x 100 mil hab."="x_100_muestras","Positivos x 100 mil hab."="x_100_positivos","Porcentaje de positivos"="x_contagio")%>%
  DT::datatable(
    options = list(pageLength = 10, 
                   lengthMenu = c(10, 15, 20),
                   language = list(lengthMenu = "Mostrar _MENU_ entradas",
                                   info ="Mostrando _START_ al _END_ de _TOTAL_ entradas",
                                   search = "Buscar:",
                                   paginate = list(previous = "Anterior",
                                                   'next' = "Siguiente"))
                   ),
    rownames = FALSE
  )

```

<p>
<div style="text-align:right"> Datos actualizados al 30/04/2020. Fuente: Sala Situacional-MINSA </div>
</p>


#### 3.1.2. Transferencias a Gobiernos regionales y su ejecución

```{r, echo=FALSE,eval=TRUE,warning=FALSE,message=FALSE,error=FALSE}
### cargar datos

regioneslink="https://docs.google.com/spreadsheets/d/e/2PACX-1vQkc4tZ-ZXIUtZ6CZPEarncXxE3lFMD8Tp4MahTcc-hMw2XdAbn5nSPLFwvM-6YoAv3l05t9ggK0bv-/pub?gid=1102095429&single=true&output=csv"

regiones=as.data.frame(read.csv(regioneslink, dec = ","))

transferencias<-regiones[!is.na(regiones$transferencias_covid),]

transferencias$ejecutado=transferencias$transferencias_covid*transferencias$x_presupuesto_covid 

### contruir tabla
#install.packages("dplyr")
library(dplyr)
transferencias%>%
  dplyr::select("Región"="region","Transferencias"="transferencias_covid", "Presupuesto ejecutado"="ejecutado", "Porcentaje de presupuesto ejecutado"="x_presupuesto_covid")%>%
  DT::datatable(
    options = list(pageLength = 10, 
                   lengthMenu = c(10, 15, 20),
                   language = list(lengthMenu = "Mostrar _MENU_ entradas",
                                   info ="Mostrando _START_ al _END_ de _TOTAL_ entradas",
                                   search = "Buscar:",
                                   paginate = list(previous = "Anterior",
                                                   'next' = "Siguiente"))
                   ),
    rownames = FALSE
  )

```

<p>
<div style="text-align:right"> Datos actualizados al 01/05/2020. Fuente: Consulta amigable - MEF </div>
</p>


#### 3.1.3. Presencia de casos positivos y nivel de gasto de los Gobiernos Regionales

```{r, echo=FALSE, eval=TRUE}

#cor.test(transferencias$x_contagio,transferencias$x_presupuesto_covid)

library(ggplot2)

p<-ggplot(transferencias, aes(x_contagio,x_presupuesto_covid)) + geom_point(aes(size=casos_positivos, colour = macroregion )) + theme_classic()+ labs(x = "Positividad a nivel regional (%)",y = "Ejecución de transferencias regionales (%)")

p
```





```{r, include=F}
### 3.2. Municipalidades provinciales


#install.packages("maptools")
#library(maptools)

#mapa provincias <- readShapeSpatial("DEPARTAMENTOS.shp")
```



```{r, include=F}
### 3.3. Municipalidades distritales

#install.packages("maptools")
#library(maptools)

#mapa distritos <- readShapeSpatial("DEPARTAMENTOS.shp")
```





```{r, include=F}

### 3.4. Lima Metropolitana y Callao

#install.packages("maptools")
#library(maptools)

#mapa sobre las acciones que han emprendido diferentes distritos en Lima

### 3.5. Labores del Comando COVID en las regiones


### 3.6. Transparencia y denuncias de corrupción a nivel subnacional


### 3.7. Retorno a las regiones


### 3.8 Buenas practicas a nivel subnacional
```

